/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put: operations["upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhook/lead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Website lead intake (HMAC-signed)
         * @description Public endpoint for the website enquiry form. Signature header X-Webhook-Signature: sha256=<hex> computed over the raw body with the shared webhook secret.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trips (default: active only, for filters/pickers) */
        get: operations["list_1"];
        put?: never;
        /** Create a catalogue trip */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List batches of a trip */
        get: operations["listBatches"];
        put?: never;
        /** Create a departure batch on a FIXED_BATCH trip */
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment lines (scoped; booking / status / type filters) */
        get: operations["list_2"];
        put?: never;
        /** Record a payment line (advance / balance / full) against a booking */
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}/trip-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the trip sheet as generated (regenerating refreshes the timestamp) */
        post: operations["generateTripSheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a timestamped note to the handoff */
        post: operations["appendNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all my notifications read */
        post: operations["markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List leads (filtered; SALES/OPS see only their own) */
        get: operations["list_3"];
        put?: never;
        /** Create a lead */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List guides (active by default) */
        get: operations["list_4"];
        put?: never;
        /** Create a guide */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings (SALES see only their own; filters optional) */
        get: operations["list_5"];
        put?: never;
        /** Create a booking (FIXED_BATCH holds seats; CUSTOM_FIT is private) */
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (rate-limited: 5 attempts / IP / 15 min) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip with its departure batches */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a trip */
        patch: operations["update"];
        trace?: never;
    };
    "/api/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a task completed */
        patch: operations["complete"];
        trace?: never;
    };
    "/api/payments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance a payment line: PENDING -> PARTIAL/COMPLETED/CANCELLED, PARTIAL -> COMPLETED/REFUNDED, COMPLETED -> REFUNDED (paidAt required for COMPLETED) */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/operations/{id}/arrangements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update arrangements: hotel / transport status, guide, driver */
        patch: operations["updateArrangements"];
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark one notification read */
        patch: operations["markRead"];
        trace?: never;
    };
    "/api/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one lead */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit lead fields (heat recomputed, per-field audit) */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/leads/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change lead status (audited; LOST requires lostReason) */
        patch: operations["updateStatus_1"];
        trace?: never;
    };
    "/api/guides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a guide */
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer detail incl. trip history + marketing flags */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update marketing flags: suggest-offer, remarketing tags, opt-in, notes */
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/bookings/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance a booking: QUOTATION -> CONFIRMED (seats), -> CANCELLED (seats released), CONFIRMED -> COMPLETED */
        patch: operations["updateStatus_2"];
        trace?: never;
    };
    "/api/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a departure batch (capacity/date/guide/transport/status) */
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/users/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List follow-up tasks (SALES see own; managers see all) */
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/booking/{bookingId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receivable statement for a booking (gross, net, applied, balance) */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ops handoffs (SALES see only their own bookings' handoffs; filters optional) */
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one ops handoff (booking context, arrangements, receivable status, notes) */
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My notification feed (newest first) */
        get: operations["list_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lead activity timeline (from audit_log) */
        get: operations["activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["performance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers — search by name/mobile/email */
        get: operations["list_9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a booking with travellers */
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TargetUpsertRequest: {
            /** Format: uuid */
            userId?: string;
            month: string;
            /** Format: int32 */
            targetBookings?: number;
            targetRevenue?: number;
        };
        UserPrincipal: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "SALES" | "OPS" | "MANAGER" | "ADMIN" | "CEO";
            active?: boolean;
        };
        TargetDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            userFullName?: string;
            /** Format: date */
            month?: string;
            /** Format: int32 */
            targetBookings?: number;
            targetRevenue?: number;
            /** Format: int64 */
            achievedBookings?: number;
            achievedRevenue?: number;
            /** Format: int32 */
            bookingsPct?: number;
            /** Format: int32 */
            revenuePct?: number;
        };
        WebhookLeadResponse: {
            ok?: boolean;
            duplicate?: boolean;
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
            note?: string;
        };
        TripCreateRequest: {
            name: string;
            slug?: string;
            /** @enum {string} */
            category: "TREK" | "PILGRIMAGE" | "LEISURE" | "CUSTOM";
            /** @enum {string} */
            bookingType: "FIXED_BATCH" | "CUSTOM_FIT";
            baseCost: number;
            /** Format: int32 */
            durationDays: number;
            itinerary?: string;
            inclusions?: string;
            exclusions?: string;
        };
        BatchResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tripId?: string;
            /** Format: date */
            departureDate?: string;
            /** Format: int32 */
            maxCapacity?: number;
            /** Format: int32 */
            seatsBooked?: number;
            /** Format: int32 */
            available?: number;
            /** Format: uuid */
            guideId?: string;
            guideName?: string;
            transportPlan?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED" | "CANCELLED";
        };
        TripDetailResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            category?: "TREK" | "PILGRIMAGE" | "LEISURE" | "CUSTOM";
            /** @enum {string} */
            bookingType?: "FIXED_BATCH" | "CUSTOM_FIT";
            baseCost?: number;
            /** Format: int32 */
            durationDays?: number;
            itinerary?: string;
            inclusions?: string;
            exclusions?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            batches?: components["schemas"]["BatchResponse"][];
        };
        BatchCreateRequest: {
            /** Format: date */
            departureDate: string;
            /** Format: int32 */
            maxCapacity: number;
            /** Format: uuid */
            guideId?: string;
            transportPlan?: string;
        };
        PaymentCreateRequest: {
            /** Format: uuid */
            bookingId: string;
            amount: number;
            /** @enum {string} */
            amountType: "ADVANCE" | "BALANCE" | "FULL";
            /** Format: date */
            dueDate?: string;
            gatewayRef?: string;
            notes?: string;
        };
        PaymentResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookingId?: string;
            bookingRef?: string;
            customerName?: string;
            amount?: number;
            /** @enum {string} */
            amountType?: "ADVANCE" | "BALANCE" | "FULL";
            /** @enum {string} */
            status?: "PENDING" | "PARTIAL" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "REFUNDED";
            /** Format: date */
            dueDate?: string;
            /** Format: date-time */
            paidAt?: string;
            gatewayRef?: string;
            notes?: string;
            /** Format: uuid */
            recordedBy?: string;
            recordedByName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OperationsHandoffResponse: {
            /** Format: uuid */
            id?: string;
            opsRef?: string;
            /** Format: uuid */
            bookingId?: string;
            bookingRef?: string;
            /** Format: uuid */
            tripId?: string;
            tripName?: string;
            /** Format: uuid */
            batchId?: string;
            /** Format: date */
            travelDate?: string;
            /** Format: int32 */
            pax?: number;
            /** @enum {string} */
            hotelStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
            /** @enum {string} */
            transportStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
            /** Format: uuid */
            guideId?: string;
            guideName?: string;
            /** Format: uuid */
            driverId?: string;
            /** @enum {string} */
            paymentStatus?: "PENDING" | "PARTIAL" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "REFUNDED";
            /** Format: date-time */
            tripSheetGeneratedAt?: string;
            notes?: string;
            /** Format: uuid */
            customerId?: string;
            customerName?: string;
            /** Format: uuid */
            createdBy?: string;
            createdByName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OpsNoteRequest: {
            note: string;
        };
        LeadCreateRequest: {
            customerName: string;
            mobileNumber: string;
            whatsappNumber?: string;
            email?: string;
            /** @enum {string} */
            source: "GOOGLE_ADS" | "FACEBOOK_ADS" | "INSTAGRAM" | "WEBSITE" | "WHATSAPP" | "REFERRAL" | "JUSTDIAL" | "WALK_IN" | "B2B" | "EXISTING_CUSTOMER" | "OTHER";
            destination?: string;
            /** Format: uuid */
            tripId?: string;
            /** Format: date */
            travelDate?: string;
            /** Format: int32 */
            numPersons?: number;
            budget?: number;
            /** Format: uuid */
            ownerId?: string;
            /** Format: date */
            followUpDate?: string;
            remarks?: string;
            consentGiven: boolean;
            consentScope?: string;
        };
        LeadResponse: {
            /** Format: uuid */
            id?: string;
            customerName?: string;
            mobileNumber?: string;
            whatsappNumber?: string;
            email?: string;
            /** @enum {string} */
            source?: "GOOGLE_ADS" | "FACEBOOK_ADS" | "INSTAGRAM" | "WEBSITE" | "WHATSAPP" | "REFERRAL" | "JUSTDIAL" | "WALK_IN" | "B2B" | "EXISTING_CUSTOMER" | "OTHER";
            destination?: string;
            /** Format: uuid */
            tripId?: string;
            /** Format: date */
            travelDate?: string;
            /** Format: int32 */
            numPersons?: number;
            budget?: number;
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
            /** Format: uuid */
            customer360Id?: string;
            /** @enum {string} */
            status?: "NEW" | "INTERESTED" | "QUOTATION_SENT" | "BOOKING_CONFIRMED" | "LOST";
            /** @enum {string} */
            heat?: "HOT" | "WARM" | "COLD";
            /** Format: date */
            followUpDate?: string;
            remarks?: string;
            consentGiven?: boolean;
            consentScope?: string;
            /** Format: date-time */
            consentCapturedAt?: string;
            /** @enum {string} */
            lostReason?: "PRICE_TOO_HIGH" | "DATES_UNAVAILABLE" | "CHOSE_COMPETITOR" | "WENT_SILENT" | "NOT_GENUINE" | "POSTPONED";
            /** Format: uuid */
            duplicateOfLeadId?: string;
            /** Format: date-time */
            lastContactedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        GuideCreateRequest: {
            fullName: string;
            phone?: string;
            dailyRate?: number;
        };
        GuideResponse: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            phone?: string;
            dailyRate?: number;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        BookingCreateRequest: {
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            batchId?: string;
            /** Format: date */
            travelDate?: string;
            /** Format: int32 */
            numTravellers?: number;
            discountAmount?: number;
            notes?: string;
            travellers?: components["schemas"]["TravellerInput"][];
        };
        TravellerInput: {
            fullName: string;
            /** Format: int32 */
            age?: number;
            gender?: string;
            phone?: string;
            medicalCertRequired?: boolean;
        };
        BookingResponse: {
            /** Format: uuid */
            id?: string;
            bookingRef?: string;
            /** Format: uuid */
            tripId?: string;
            tripName?: string;
            /** Format: uuid */
            batchId?: string;
            /** Format: date */
            departureDate?: string;
            /** Format: uuid */
            customerId?: string;
            customerName?: string;
            customerPhone?: string;
            /** @enum {string} */
            bookingType?: "FIXED_BATCH" | "CUSTOM_FIT";
            /** Format: int32 */
            numTravellers?: number;
            totalAmount?: number;
            discountAmount?: number;
            taxAmount?: number;
            netAmount?: number;
            /** @enum {string} */
            status?: "QUOTATION" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
            /** Format: date */
            travelDate?: string;
            /** Format: uuid */
            discountApprovedBy?: string;
            notes?: string;
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            createdBy?: string;
            createdByName?: string;
            travellers?: components["schemas"]["TravellerResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TravellerResponse: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            /** Format: int32 */
            age?: number;
            gender?: string;
            phone?: string;
            medicalCertRequired?: boolean;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            user?: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "SALES" | "OPS" | "MANAGER" | "ADMIN" | "CEO";
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        TripUpdateRequest: {
            name?: string;
            slug?: string;
            /** @enum {string} */
            category?: "TREK" | "PILGRIMAGE" | "LEISURE" | "CUSTOM";
            /** @enum {string} */
            bookingType?: "FIXED_BATCH" | "CUSTOM_FIT";
            baseCost?: number;
            /** Format: int32 */
            durationDays?: number;
            itinerary?: string;
            inclusions?: string;
            exclusions?: string;
            active?: boolean;
        };
        TaskResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            leadId?: string;
            customerName?: string;
            /** Format: uuid */
            assigneeId?: string;
            assigneeName?: string;
            /** @enum {string} */
            type?: "INITIAL_CALL" | "FOLLOW_UP_1D" | "FOLLOW_UP_3D" | "FOLLOW_UP_8D" | "FOLLOW_UP_15D" | "QUOTATION" | "PAYMENT_REMINDER" | "OPS" | "REVIEW" | "CUSTOM";
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED" | "OVERDUE" | "CANCELLED";
            /** Format: date-time */
            dueAt?: string;
            /** Format: date-time */
            slaDeadline?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            escalatedAt?: string;
            notes?: string;
        };
        PaymentStatusRequest: {
            /** @enum {string} */
            status: "PENDING" | "PARTIAL" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "REFUNDED";
            /** Format: date-time */
            paidAt?: string;
            gatewayRef?: string;
            note?: string;
        };
        OpsArrangementsRequest: {
            /** @enum {string} */
            hotelStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
            /** @enum {string} */
            transportStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
            /** Format: uuid */
            guideId?: string;
            /** Format: uuid */
            driverId?: string;
        };
        NotificationResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            channel?: "IN_APP" | "EMAIL";
            title?: string;
            body?: string;
            link?: string;
            read?: boolean;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LeadUpdateRequest: {
            customerName?: string;
            email?: string;
            whatsappNumber?: string;
            destination?: string;
            /** Format: uuid */
            tripId?: string;
            /** Format: date */
            travelDate?: string;
            /** Format: int32 */
            numPersons?: number;
            budget?: number;
            /** Format: date */
            followUpDate?: string;
            remarks?: string;
        };
        LeadStatusRequest: {
            /** @enum {string} */
            status: "NEW" | "INTERESTED" | "QUOTATION_SENT" | "BOOKING_CONFIRMED" | "LOST";
            /** @enum {string} */
            lostReason?: "PRICE_TOO_HIGH" | "DATES_UNAVAILABLE" | "CHOSE_COMPETITOR" | "WENT_SILENT" | "NOT_GENUINE" | "POSTPONED";
            note?: string;
        };
        GuideUpdateRequest: {
            fullName?: string;
            phone?: string;
            dailyRate?: number;
            active?: boolean;
        };
        CustomerUpdateRequest: {
            suggestOffer?: string;
            offerTags?: string[];
            marketingOptIn?: boolean;
            notes?: string;
        };
        CustomerDetailResponse: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            mobileNumber?: string;
            whatsappNumber?: string;
            email?: string;
            consentGiven?: boolean;
            /** Format: date-time */
            consentCapturedAt?: string;
            consentScope?: string;
            marketingOptIn?: boolean;
            /** Format: int32 */
            totalTrips?: number;
            /** Format: date */
            lastTripDate?: string;
            totalSpent?: number;
            suggestOffer?: string;
            offerTags?: string[];
            notes?: string;
            tripHistory?: components["schemas"]["TripRow"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TripRow: {
            /** Format: uuid */
            id?: string;
            bookingRef?: string;
            /** Format: uuid */
            tripId?: string;
            tripName?: string;
            /** Format: date */
            travelDate?: string;
            /** @enum {string} */
            status?: "QUOTATION" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
            netAmount?: number;
            appliedAmount?: number;
        };
        BookingStatusRequest: {
            /** @enum {string} */
            status: "QUOTATION" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
            note?: string;
        };
        BatchUpdateRequest: {
            /** Format: date */
            departureDate?: string;
            /** Format: int32 */
            maxCapacity?: number;
            /** Format: uuid */
            guideId?: string;
            unassignGuide?: boolean;
            transportPlan?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED" | "CANCELLED";
        };
        SalesUser: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
        };
        TripResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            category?: "TREK" | "PILGRIMAGE" | "LEISURE" | "CUSTOM";
            /** @enum {string} */
            bookingType?: "FIXED_BATCH" | "CUSTOM_FIT";
            baseCost?: number;
            /** Format: int32 */
            durationDays?: number;
            active?: boolean;
        };
        Overall: {
            /** Format: int32 */
            targetBookings?: number;
            targetRevenue?: number;
            /** Format: int64 */
            achievedBookings?: number;
            achievedRevenue?: number;
            /** Format: int32 */
            bookingsPct?: number;
            /** Format: int32 */
            revenuePct?: number;
        };
        TargetListResponse: {
            /** Format: date */
            month?: string;
            targets?: components["schemas"]["TargetDto"][];
            overall?: components["schemas"]["Overall"];
        };
        TargetProgressResponse: {
            /** Format: date */
            month?: string;
            overall?: components["schemas"]["Overall"];
            employees?: components["schemas"]["TargetDto"][];
        };
        PaymentSummaryResponse: {
            /** Format: uuid */
            bookingId?: string;
            bookingRef?: string;
            customerName?: string;
            grossAmount?: number;
            discountAmount?: number;
            netAmount?: number;
            appliedAmount?: number;
            balanceAmount?: number;
            /** Format: date */
            nextDueDate?: string;
            hasOverdueLine?: boolean;
        };
        PageLeadResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["LeadResponse"][];
            /** Format: int32 */
            number?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            paged?: boolean;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        LeadActivityResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            action?: "CREATE" | "UPDATE" | "STATUS_CHANGE" | "DELETE" | "LOGIN" | "LOGOUT";
            field?: string;
            oldValue?: string;
            newValue?: string;
            actorName?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        DashboardSummaryResponse: {
            period?: string;
            /** Format: date */
            from?: string;
            /** Format: int64 */
            totalLeads?: number;
            /** Format: int64 */
            newLeads?: number;
            /** Format: int64 */
            followUpDue?: number;
            /** Format: int64 */
            interested?: number;
            /** Format: int64 */
            quotationSent?: number;
            /** Format: int64 */
            bookingConfirmed?: number;
            /** Format: int64 */
            lost?: number;
            /** Format: int64 */
            newBookings?: number;
            /** Format: int64 */
            confirmedBookings?: number;
            revenue?: number;
        };
        Employee: {
            /** Format: uuid */
            userId?: string;
            fullName?: string;
            email?: string;
            /** Format: int64 */
            leadsAssigned?: number;
            /** Format: int64 */
            followUpsCompleted?: number;
            /** Format: int64 */
            bookingsClosed?: number;
            /** Format: int64 */
            paymentsCount?: number;
            revenue?: number;
        };
        PerformanceResponse: {
            month?: string;
            employees?: components["schemas"]["Employee"][];
            totals?: components["schemas"]["Totals"];
        };
        Totals: {
            /** Format: int64 */
            leadsAssigned?: number;
            /** Format: int64 */
            followUpsCompleted?: number;
            /** Format: int64 */
            bookingsClosed?: number;
            revenue?: number;
        };
        CustomerListResponse: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            mobileNumber?: string;
            email?: string;
            marketingOptIn?: boolean;
            consentGiven?: boolean;
            /** Format: int32 */
            totalTrips?: number;
            /** Format: date */
            lastTripDate?: string;
            totalSpent?: number;
            suggestOffer?: string;
            offerTags?: string[];
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query: {
                month?: string;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TargetListResponse"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetUpsertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TargetDto"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Webhook-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Duplicate lead already active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
            /** @description Lead created; owner assigned; 5-min call task scheduled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
            /** @description Invalid payload / missing consent */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
            /** @description Missing or invalid HMAC signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
            /** @description No sales user available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookLeadResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
        };
    };
    listBatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"][];
                };
            };
        };
    };
    createBatch: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                bookingId?: string;
                status?: "PENDING" | "PARTIAL" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "REFUNDED";
                amountType?: "ADVANCE" | "BALANCE" | "FULL";
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"][];
                };
            };
        };
    };
    record: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    generateTripSheet: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsHandoffResponse"];
                };
            };
        };
    };
    appendNote: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsNoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsHandoffResponse"];
                };
            };
        };
    };
    markAllRead: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    list_3: {
        parameters: {
            query: {
                ownerId?: string;
                status?: "NEW" | "INTERESTED" | "QUOTATION_SENT" | "BOOKING_CONFIRMED" | "LOST";
                source?: "GOOGLE_ADS" | "FACEBOOK_ADS" | "INSTAGRAM" | "WEBSITE" | "WHATSAPP" | "REFERRAL" | "JUSTDIAL" | "WALK_IN" | "B2B" | "EXISTING_CUSTOMER" | "OTHER";
                heat?: "HOT" | "WARM" | "COLD";
                tripId?: string;
                from?: string;
                to?: string;
                travelFrom?: string;
                travelTo?: string;
                search?: string;
                page?: number;
                size?: number;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageLeadResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query: {
                tripId?: string;
                batchId?: string;
                customerId?: string;
                status?: "QUOTATION" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    updateArrangements: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsArrangementsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsHandoffResponse"];
                };
            };
        };
    };
    markRead: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    updateStatus_1: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetailResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetailResponse"];
                };
            };
        };
    };
    updateStatus_2: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
        };
    };
    sales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesUser"][];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query: {
                leadId?: string;
                status?: "PENDING" | "COMPLETED" | "OVERDUE" | "CANCELLED";
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    progress: {
        parameters: {
            query: {
                month?: string;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TargetProgressResponse"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSummaryResponse"];
                };
            };
        };
    };
    list_7: {
        parameters: {
            query: {
                travelDateFrom?: string;
                travelDateTo?: string;
                hotelStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
                transportStatus?: "NOT_ARRANGED" | "PENDING" | "CONFIRMED";
                paymentStatus?: "PENDING" | "PARTIAL" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "REFUNDED";
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsHandoffResponse"][];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsHandoffResponse"];
                };
            };
        };
    };
    list_8: {
        parameters: {
            query: {
                unreadOnly?: boolean;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    activity: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadActivityResponse"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    summary_1: {
        parameters: {
            query: {
                period?: string;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
    performance: {
        parameters: {
            query: {
                month?: string;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PerformanceResponse"];
                };
            };
        };
    };
    list_9: {
        parameters: {
            query: {
                search?: string;
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"][];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query: {
                caller: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query: {
                principal: components["schemas"]["UserPrincipal"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
